spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/transactionrisk}
    username: ${DB_USERNAME:transactionrisk}
    password: ${DB_PASSWORD:transactionrisk}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
